apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: default
  labels:
    app: service-label
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-label
  type: ClusterIP