apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-name
  namespace: default
  labels:
    app: replicaset-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: demo-container
        image: gcr.io/neat-responder-349115/demo-app:sydney