apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: default
  labels:
    app: pod-label
spec:
  containers:
  - name: demo-container
    image: gcr.io/neat-responder-349115/demo-app:sydney
    ports:
    - containerPort: 80
