apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  namespace: default
  labels:
    app: deployment-label
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: demo-container
        image: gcr.io/neat-responder-349115/demo-app:sydney
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst